import type { Student, Payment, Sale } from './types';

export const students: Student[] = [
  {
    id: '1',
    name: 'Ana Silva',
    dob: '1995-03-12',
    cpf: '123.456.789-01',
    clothingSizes: { shirt: 'M', pants: '38' },
    contactInfo: { email: 'ana.silva@example.com', phone: '(11) 98765-4321' },
    emergencyContacts: [{ name: 'Carlos Silva', phone: '(11) 12345-6789', relationship: 'Father' }],
    startDate: '2023-01-15',
    lastGradingDate: '2023-11-20',
    belt: 'Green',
    medicalHistory: 'No known allergies. Had a minor knee sprain in 2022.',
    notes: 'Very dedicated student, shows great potential.',
    status: 'Active',
    fikmFeePaid: true,
    performanceData: 'Excellent performance in sparring, needs to improve on ground techniques.',
    avatarUrl: 'https://picsum.photos/seed/s1/200/200',
  },
  {
    id: '2',
    name: 'Bruno Costa',
    dob: '1988-07-25',
    cpf: '234.567.890-12',
    clothingSizes: { shirt: 'L', pants: '42' },
    contactInfo: { email: 'bruno.costa@example.com', phone: '(21) 91234-5678' },
    emergencyContacts: [{ name: 'Maria Costa', phone: '(21) 87654-3210', relationship: 'Wife' }],
    startDate: '2022-05-10',
    belt: 'Blue',
    medicalHistory: 'Asthma, carries an inhaler.',
    notes: 'Struggles with cardio, but has powerful strikes.',
    status: 'Active',
    fikmFeePaid: true,
    performanceData: 'High accuracy on striking drills. Stamina drops quickly during prolonged exercises.',
    avatarUrl: 'https://picsum.photos/seed/s2/200/200',
  },
  {
    id: '3',
    name: 'Carla Dias',
    dob: '2001-11-30',
    cpf: '345.678.901-23',
    clothingSizes: { shirt: 'S', pants: '36' },
    contactInfo: { email: 'carla.dias@example.com', phone: '(31) 95678-1234' },
    emergencyContacts: [{ name: 'Joana Dias', phone: '(31) 43210-8765', relationship: 'Mother' }],
    startDate: '2023-08-01',
    belt: 'Yellow',
    medicalHistory: '',
    notes: 'Good flexibility and quick learner.',
    status: 'Active',
    fikmFeePaid: false,
    performanceData: 'Masters new techniques quickly. Lacks confidence in applying them under pressure.',
    avatarUrl: 'https://picsum.photos/seed/s3/200/200',
  },
  {
    id: '4',
    name: 'Daniel Almeida',
    dob: '1992-09-18',
    cpf: '456.789.012-34',
    clothingSizes: { shirt: 'XL', pants: '44' },
    contactInfo: { email: 'daniel.almeida@example.com', phone: '(41) 98765-1234' },
    emergencyContacts: [{ name: 'Ricardo Almeida', phone: '(41) 12345-8765', relationship: 'Brother' }],
    startDate: '2021-02-20',
    belt: 'Brown',
    medicalHistory: 'Shoulder surgery in 2019. Avoids overhead lifts.',
    notes: 'Experienced martial artist, transitioning from Karate.',
    status: 'Inactive',
    fikmFeePaid: true,
    performanceData: 'Strong stance and footwork. Needs to adapt to Krav Maga\'s simultaneous block-and-strike principles.',
    avatarUrl: 'https://picsum.photos/seed/s4/200/200',
  },
  {
    id: '5',
    name: 'Eduarda Lima',
    dob: '1999-01-05',
    cpf: '567.890.123-45',
    clothingSizes: { shirt: 'M', pants: '40' },
    contactInfo: { email: 'eduarda.lima@example.com', phone: '(51) 91234-8765' },
    emergencyContacts: [{ name: 'Fernanda Lima', phone: '(51) 56789-4321', relationship: 'Sister' }],
    startDate: '2024-01-10',
    belt: 'White',
    medicalHistory: 'None',
    notes: 'New student, very enthusiastic.',
    status: 'Active',
    fikmFeePaid: true,
    performanceData: 'Beginner level. Shows good coordination.',
    avatarUrl: 'https://picsum.photos/seed/s5/200/200',
  },
];

export const payments: Payment[] = [
  { id: 'p1', studentId: '1', date: '2024-05-01', plan: { type: 'Monthly', value: 150 }, validUntil: '2024-06-01' },
  { id: 'p2', studentId: '2', date: '2024-04-10', plan: { type: 'Quarterly', value: 400 }, validUntil: '2024-07-10' },
  { id: 'p3', studentId: '3', date: '2024-03-15', plan: { type: 'Monthly', value: 150 }, validUntil: '2024-04-15' }, // Overdue
  { id: 'p4', studentId: '4', date: '2023-12-01', plan: { type: 'Monthly', value: 150 }, validUntil: '2024-01-01' },
  { id: 'p5', studentId: '5', date: '2024-05-05', plan: { type: 'Monthly', value: 150 }, validUntil: '2024-06-05' },
];

export const sales: Sale[] = [
    { id: 'sa1', studentId: '1', studentName: 'Ana Silva', date: '2024-02-20', item: 'Uniform', value: 250 },
    { id: 'sa2', studentId: '3', studentName: 'Carla Dias', date: '2024-03-05', item: 'Book - "Krav Maga Fundamentals"', value: 80 },
    { id: 'sa3', studentId: '2', studentName: 'Bruno Costa', date: '2024-04-11', item: 'Protein Supplement', value: 120 },
    { id: 'sa4', studentId: '5', studentName: 'Eduarda Lima', date: '2024-05-15', item: 'Uniform', value: 250 },
];

export const getStudentById = (id: string) => students.find(s => s.id === id);
export const getPaymentsByStudentId = (studentId: string) => payments.filter(p => p.studentId === studentId);
